### PR TITLE
[BC] use case insensitive values

### PR DESCRIPTION
**Pull request by Gummibeer**
**related to:** #13

### CODE REVIEW

**Comment by eclipxe13** [comment]
In order to understand. Why values are also changing to lower case?

**Comment by Gummibeer** [comment]
You mean why it's `hello => hello` and not `hello => Hello`? Haven't thought about it - the fact that the map values are also not touched would mean that we also shouldn't touch the auto-gen values, right!?

I will change this.

**Comment by eclipxe13** [comment]
Yes. That is what I meant. IMO they should be set as original method definition.

**Comment by brendt** [comment]
I would expect `$map` to support both:

```php
$map = [
    'DrAfT' => '0'
];
```

Should work fine.

**Comment by eclipxe13** [comment]
The key of map is only used for getting a default value, isn't it? You might require to be lower case in definition or search for the key ignoring case and use the value.

**Comment by eclipxe13** [comment]
Reintroducing findKeyInMapIgnoringCase 😕

**Comment by Gummibeer** [comment]
@brendt so lets stick to the two examples in the unittest.
Should the map-key be lower-cased or should t stay as it is:
```php
$map = [
  'Hello' => 'hellovalue',
  'WORLD' => 'worldvalue',
];
// VS
$map = [
  'hello' => 'hellovalue',
  'world' => 'worldvalue',
];
```

**Comment by eclipxe13** [comment]
I think the only working situation should be

    $map = [
      'Hello' => 'hellovalue',
      'WORLD' => 'worldvalue',
    ];

As defined in docblock or static method.

**Comment by Gummibeer** [comment]
Ok, so this is now the case :) I would say that this PR is ready for review.^^

**Comment by brendt** [comment]
Fair enough, looks good. Thanks both!

**Comment by brendt** [comment]
Tagged as https://github.com/spatie/enum/releases/tag/1.0.2

**Pull request merged**
