### PR TITLE
Minor note about overriding default values...

### PR DESCRIPTION
**Pull request by telkins**
I added a minor note about overriding default values...once I discovered that this could be done.  (I was happy to discover this because I was not happy listing all of the values just to override one of them, for example.)

Anyway, I wasn't too happy with the wording....so someone may have a better way of putting it so that it's clear and concise like the rest of the docs.

I also broke up a couple of sentences in the section on labels.  To me, it reads better broken up....two different thoughts.

Please let me know if you have any questions/concerns.

Thx.  🤓

### CODE REVIEW

**Review by Gummibeer — APPROVED** [review]
Sounds good to me! 🙂
Thanks for the improvement! 🎉

**Comment by Gummibeer** [comment]
As you seem to be one overriding the values/labels. 🙈😂
Something I'm primarily doing is converting all values to lowercase, or things like that.
As I don't have access to the method names in the two mapping methods I have to list every value instead of doing `array_map()`.

What do you think about something that allows you to automatically apply any manipulation on the defined method names to map values/labels? 🤔

**Comment by telkins** [comment]
> Something I'm primarily doing is converting all values to lowercase, or things like that.

Same here, more or less.  My preference is to have my enums lower- and kebab-case.

> As I don't have access to the method names in the two mapping methods I have to list every value instead of doing `array_map()`.

Sorry....not sure what you mean by this...."the two mapping methods".  I'm guessing you're talking about the `Enum` class itself, but I'm not connecting the dots. 😳 

> What do you think about something that allows you to automatically apply any manipulation on the defined method names to map values/labels? 🤔

I was thinking of asking about this before potentially working on and submitting a PR....but then I remembered that this was a "generic" PHP package and my brain's been simmering in Laravel for several years now, so my ideas won't work.  I hadn't thought past that, though.

Whatever the case, I think it would be a good idea.  I think this package is quite nice and it gives people what they need ("overriding the values/labels"), but it doesn't quite feel as nice or -- I hate to use the overused word...! -- "elegant" as it could be.

So....that was the long answer.  **The short answer: Yes, I think it would be a great idea...!**  👍 

May I ask what you had in mind...? 🤔

**Comment by Gummibeer** [comment]
The easiest adjustment would be `values(array<string, string> $values): array<string, string>`. But as far as I remember PHP signatures this would be breaking. 😔
So the values have to be published to`static` before the method is called. 🤔

I will check source code again and think about a solution that isn't breaking but allows something like `return array_map('strtolower', $values)` instead of a large copy'n'paste array.

Thanks for your feedback! 😊
Hope you enjoy our Laravel wrapper as well!? 😉

**Comment by telkins** [comment]
> The easiest adjustment would be `values(array<string, string> $values): array<string, string>`. But as far as I remember PHP signatures this would be breaking. 😔
> So the values have to be published to`static` before the method is called. 🤔

LOL!  Sorry, but your notation, `values(array<string, string> $values): array<string, string>`, didn't exactly make sense to me.  I can see the first part is similar to the psalm annotation on the static `values()` method....but beyond that, I can't quite follow you.  I am interested, though, if you have the patience to spell out a little more clearly what you mean.  🤓 

> I will check source code again and think about a solution that isn't breaking but allows something like `return array_map('strtolower', $values)` instead of a large copy'n'paste array.

I'm not sure that it addresses the issues you are talking about above, but one of the things I was thinking about was a static property that could hold a list of "filters".....so the values (method names by default to begin with, as it is today) could be passed through the "filters" before being returned.  No filters means the values would be the method names.

The filters could be whatever....but simple closures and/or classes that implement a specific interface.  Perhaps there are other ideas.

A solution like this would not break things and would be doable with plain ol' PHP.  One downside, IMO, is that the filters would need to be for the `Enum` class and not individual enums.  This is fine for me since I am pretty sure I'd want to treat all enums the same....but there may be others that might want differences between enums.  Don't know....

What do you think...?

> Thanks for your feedback! 😊

NP....I enjoy this kind of stuff.  🤓 

> Hope you enjoy our Laravel wrapper as well!? 😉

Yes....of course.  😁

**Pull request merged**
