### PR TITLE
Added description to assert methods, based on readme file

### PR DESCRIPTION
**Pull request by riwiki**
Hey there,
I am using your awesome package and I love it, thank you so much!
While using your assertions in unit tests, I found myself wondering what each method does and saw that you described them in the readme. To have it closer to code when being in the IDE, I copied (and slightly modified) them over to the PhpDoc. Hope my changes are an improvement.

This is my first pull request ever and really excited :D

Greetings from Germany, Trier

### CODE REVIEW

**Review by Gummibeer — APPROVED** [review]

**Comment by brendt** [comment]
Nice, feel free to merge @Gummibeer , no need for my approval for these kinds of PRs :)

**Comment by Gummibeer** [comment]
Haven't waited for your approval. But wasn't able to merge. 😥
https://gummibeer.dev/blog/2021/yoda

**Comment by riwiki** [comment]
Hey Tom, I just read your blog post, and I feel very grateful. I am also very sorry for your loss, but at the same time very grateful for the wise advice you gave, your courage and your vulnerability. I am grateful that you shared this. I wish you the best. May all the good feelings with Yoda stay with you forever.

**Comment by Gummibeer** [comment]
Hey, sorry for the massive delay. 🙈
I've will check again in detail and merge afterward.
Thanks for your PR! 🥳

**Review by Gummibeer — APPROVED** [review]

**Comment by Gummibeer** [comment]
https://github.com/spatie/enum/releases/tag/3.7.1

**Pull request merged**
