### PR TITLE
allow to return a closure to map values and labels

### PR DESCRIPTION
**Pull request by Gummibeer**
replaces #83
fixes #83

### CODE REVIEW

**Review by ahmedsayedabdelsalam — APPROVED** [review]

**Comment by Gummibeer** [comment]
@brendt could you review the changes.
They shouldn't be breaking as I've dropped a native return type-hint but it's still compatible as I've only added a new possible return type.
Or should we switch to PHP `^8.0` only here and use native return type-hints for the new union types?
In my opinion, if it's wanted to drop PHP7.4, I would favor a 7.4 compatible release of this feature and afterward drop 7.4 and update the type-hints everywhere.

**Comment by brendt** [comment]
Hi Tom, looks great as well. I'd keep PHP 7.4 support for a little while longer. Feel free to merge, looks perfect!

**Review by brendt — APPROVED** [review]

**Comment by brendt** [comment]
Oh one more thing: we should also update the docs once this is merged.

**Comment by Gummibeer** [comment]
Sure, will always update the docs as soon as the feature is final/merged. 😉

**Comment by Gummibeer** [comment]
https://github.com/spatie/enum/releases/tag/3.7.0

**Pull request merged**
