### PR TITLE
use getName() instead of property

### PR DESCRIPTION
**Pull request by Gummibeer**

### CODE REVIEW

**Comment by Gummibeer** [comment]
@brendt this was *too* fast 😂 
But yeah, why have I already opened this PR

**Comment by brendt** [comment]
Doesn't GitHub have "work in progress PRs" ? 😁

My thinking was that you were doing some cleanup, it looked like a valid change on its own, especially with the title of the PR.

Anyways: feel free to submit a new one ;)

**Comment by Gummibeer** [comment]
@brendt I can'T add the label - only via title. But yeah, was my fault. The PR was thought as standalone but during my own review I saw that I could reduce it more - but you've already merged it.^^

**Comment by brendt** [comment]
I meant there's a new draft PR feature baked into GH ;) https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Pull request merged**
