### PR TITLE
add phpunit enum assertions

### PR DESCRIPTION
**Pull request by Gummibeer**
This PR adds several useful Phpunit Assertions that will make it easier and more readable to test enums in applications.

### CODE REVIEW

**Comment by Gummibeer** [comment]
You can ignore the failing Scrutinizer test - it's not anymore configured and now also disabled/removed.

**Comment by Nielsvanpach** [comment]
Looks good to me! But let's wait on Brent's approval

**Comment by brendt** [comment]
Looks good!

**Comment by Gummibeer** [comment]
https://github.com/spatie/enum/releases/tag/3.3.0

**Pull request merged**
